apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gkerlove-agent-athena
  name: gkerlove-agent-athena
  namespace: gker-love
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gkerlove-agent-athena
  template:
    metadata:
      labels:
        app: gkerlove-agent-athena
    spec:
      imagePullSecrets:
        - name: alibaba-docker-registry-secret
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/gkerlove-agent:SNAPSHOT-$BUILD_NUMBER
          imagePullPolicy: Always
          name: app
          env:
          - name: USER_CLASS
            value: Athena
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai
                key: apiKey
          - name: PASSWORD_ATHENA
            valueFrom:
              secretKeyRef:
                name: agent-password
                key: Athena
          - name: GAODE_API_KEY
            valueFrom:
              secretKeyRef:
                name: gaode
                key: apiKey
          - name: LANGCHAIN_API_KEY
            valueFrom:
              secretKeyRef:
                name: langchain
                key: apiKey
          - name: LANGCHAIN_TRACING_V2
            value: "true"
          - name: BING_SUBSCRIPTION_KEY
            valueFrom:
              secretKeyRef:
                name: bing
                key: subscriptionKey
          - name: BING_SEARCH_URL
            value: https://api.bing.microsoft.com/v7.0/search
          volumeMounts:
          - name: host-time
            mountPath: /etc/localtime